program: generic_training.py
method: random
metric:
  name: mean_val_loss
  goal: minimize
parameters:
  batch_size:
    values : [4,8]
  learning_rate:
    min: 0.00001
    max: 0.01
    distribution: uniform
  num_epochs:
    value: 250
  criterion:
    values: ['bce_loss', 'dice_loss']
  model:
    value: 'unet'
  training_path:
    value: "../data/csv_files/train.csv"
  validation_path:
    value: "../data/csv_files/val.csv"
  max_non_improvement_epochs:
    value: 60
  min_val_iou_for_saving:
    value: 0.70



